### ISSUE TITLE
MonthTest JUnit test failed

### ISSUE THREAD

**Issue by DJViking** [jfree/jfreechart#46] opened 2017-03-21 11:42 UTC
Failed tests:   testParseMonth(org.jfree.data.time.MonthTest): expected:<3> but was:<1>

Change what I thought was wrong and got no further problems

diff --git a/src/test/java/org/jfree/data/time/MonthTest.java b/src/test/java/org/jfree/data/time/MonthTest.java
index 91dc9c22..1733f222 100644
--- a/src/test/java/org/jfree/data/time/MonthTest.java
+++ b/src/test/java/org/jfree/data/time/MonthTest.java
@@ -218,7 +218,7 @@ public class MonthTest {
             month = Month.parseMonth("02-1991");
         }
         catch (TimePeriodFormatException e) {
'-            month = new Month(1, 1900);
'+            month = new Month(2, 1991);
         }
         assertEquals(2, month.getMonth());
         assertEquals(1991, month.getYear().getYear());
@@ -228,7 +228,7 @@ public class MonthTest {
             month = Month.parseMonth("March 1993");
         }
         catch (TimePeriodFormatException e) {
'-            month = new Month(1, 1900);
'+            month = new Month(3, 1993);
         }
         assertEquals(3, month.getMonth());
         assertEquals(1993, month.getYear().getYear());

**Comment by simon04** [comment] 2017-05-19 09:33
Duplicate of #33.

**Comment by jfree** [comment] 2017-07-08 07:33
Closing as a duplicate.

**Closed by jfree** 2017-07-08 07:33 UTC
