### ISSUE TITLE
Please help to publish a new version, the current version is too old

### ISSUE THREAD

**Issue by youngrass** [jfree/jfreechart#157] opened 2020-04-23 02:44 UTC
The current versions of jfreechart and jcommon are both released in 2017, which is almost 3 years old, and there is a plan to release 1.6.0. Please release the new version, thank you.

**Comment by lemming622** [comment] 2020-05-11 15:28
duplicate of #147

**Comment by jfree** [comment] 2020-10-23 04:09
Working on it.

**Closed by jfree** 2020-10-23 04:09 UTC
